from app.models import Location, Place


PLACES: list[Place] = [
    Place(
        id="cafe-neo-vi",
        name="Cafe Neo Victoria Island",
        category="Coffee",
        area="Victoria Island",
        location=Location(lat=6.4281, lng=3.4219),
        price_level=2,
        typical_spend=8500,
        rating=4.4,
        opens_at=7,
        closes_at=22,
        wifi=4,
        power=4,
        quietness=3,
        seating=4,
        ambience=3,
        food=3,
        parking=True,
        security=4,
        outdoor_seating=False,
        work_friendly=5,
        date_friendly=3,
        family_friendly=3,
        tags=["wifi", "power", "coffee", "work-friendly"],
    ),
    Place(
        id="art-cafe",
        name="Art Cafe",
        category="Cafe",
        area="Victoria Island",
        location=Location(lat=6.4268, lng=3.4307),
        price_level=3,
        typical_spend=18000,
        rating=4.6,
        opens_at=8,
        closes_at=23,
        wifi=4,
        power=3,
        quietness=3,
        seating=4,
        ambience=5,
        food=4,
        parking=True,
        security=4,
        outdoor_seating=True,
        work_friendly=4,
        date_friendly=5,
        family_friendly=3,
        tags=["romantic", "artsy", "wifi", "outdoor"],
    ),
    Place(
        id="myyas-cafe",
        name="MyYa's Cafe",
        category="Cafe",
        area="Lekki Phase 1",
        location=Location(lat=6.4471, lng=3.4747),
        price_level=2,
        typical_spend=9500,
        rating=4.3,
        opens_at=8,
        closes_at=21,
        wifi=3,
        power=4,
        quietness=4,
        seating=4,
        ambience=4,
        food=4,
        parking=False,
        security=3,
        outdoor_seating=False,
        work_friendly=4,
        date_friendly=4,
        family_friendly=3,
        tags=["quiet", "brunch", "power", "work-friendly"],
    ),
    Place(
        id="workstation-vi",
        name="Workstation",
        category="Coworking",
        area="Victoria Island",
        location=Location(lat=6.4317, lng=3.4226),
        price_level=3,
        typical_spend=15000,
        rating=4.5,
        opens_at=8,
        closes_at=20,
        wifi=5,
        power=5,
        quietness=5,
        seating=5,
        ambience=3,
        food=2,
        parking=True,
        security=5,
        outdoor_seating=False,
        work_friendly=5,
        date_friendly=1,
        family_friendly=1,
        tags=["coworking", "very quiet", "reliable wifi", "power"],
    ),
    Place(
        id="freedom-park",
        name="Freedom Park",
        category="Park",
        area="Lagos Island",
        location=Location(lat=6.4479, lng=3.3958),
        price_level=1,
        typical_spend=3500,
        rating=4.2,
        opens_at=10,
        closes_at=23,
        wifi=1,
        power=1,
        quietness=3,
        seating=3,
        ambience=4,
        food=3,
        parking=True,
        security=3,
        outdoor_seating=True,
        work_friendly=1,
        date_friendly=3,
        family_friendly=4,
        tags=["outdoor", "cheap", "culture", "casual"],
    ),
    Place(
        id="rsvp",
        name="RSVP Lagos",
        category="Restaurant",
        area="Victoria Island",
        location=Location(lat=6.4284, lng=3.4221),
        price_level=4,
        typical_spend=42000,
        rating=4.7,
        opens_at=12,
        closes_at=24,
        wifi=2,
        power=2,
        quietness=3,
        seating=4,
        ambience=5,
        food=5,
        parking=True,
        security=5,
        outdoor_seating=True,
        work_friendly=1,
        date_friendly=5,
        family_friendly=2,
        tags=["romantic", "premium", "cocktails", "dinner"],
    ),
    Place(
        id="the-bistro",
        name="The Bistro",
        category="Restaurant",
        area="Lekki Phase 1",
        location=Location(lat=6.4418, lng=3.4694),
        price_level=3,
        typical_spend=26000,
        rating=4.4,
        opens_at=9,
        closes_at=23,
        wifi=3,
        power=3,
        quietness=3,
        seating=4,
        ambience=4,
        food=4,
        parking=True,
        security=4,
        outdoor_seating=True,
        work_friendly=3,
        date_friendly=4,
        family_friendly=4,
        tags=["brunch", "date-friendly", "food", "outdoor"],
    ),
    Place(
        id="lagos-library",
        name="Herbert Macaulay Library",
        category="Library",
        area="Yaba",
        location=Location(lat=6.5158, lng=3.3869),
        price_level=1,
        typical_spend=1500,
        rating=4.0,
        opens_at=9,
        closes_at=18,
        wifi=2,
        power=3,
        quietness=5,
        seating=4,
        ambience=2,
        food=1,
        parking=False,
        security=3,
        outdoor_seating=False,
        work_friendly=4,
        date_friendly=1,
        family_friendly=3,
        tags=["quiet", "reading", "cheap", "focus"],
    ),
    Place(
        id="cafe-one-yaba",
        name="Cafe One Yaba",
        category="Cafe",
        area="Yaba",
        location=Location(lat=6.5101, lng=3.3719),
        price_level=2,
        typical_spend=7000,
        rating=4.2,
        opens_at=8,
        closes_at=21,
        wifi=4,
        power=4,
        quietness=4,
        seating=4,
        ambience=3,
        food=3,
        parking=False,
        security=3,
        outdoor_seating=False,
        work_friendly=5,
        date_friendly=2,
        family_friendly=2,
        tags=["wifi", "power", "quiet", "affordable"],
    ),
    Place(
        id="yellow-chilli",
        name="Yellow Chilli",
        category="Restaurant",
        area="Victoria Island",
        location=Location(lat=6.4261, lng=3.4189),
        price_level=3,
        typical_spend=22000,
        rating=4.4,
        opens_at=11,
        closes_at=23,
        wifi=2,
        power=2,
        quietness=3,
        seating=4,
        ambience=4,
        food=5,
        parking=True,
        security=4,
        outdoor_seating=False,
        work_friendly=1,
        date_friendly=4,
        family_friendly=4,
        tags=["nigerian food", "date-friendly", "dinner"],
    ),
    Place(
        id="bogobiri",
        name="Bogobiri House",
        category="Lounge",
        area="Ikoyi",
        location=Location(lat=6.4482, lng=3.4266),
        price_level=3,
        typical_spend=20000,
        rating=4.3,
        opens_at=12,
        closes_at=24,
        wifi=2,
        power=2,
        quietness=2,
        seating=3,
        ambience=5,
        food=3,
        parking=True,
        security=4,
        outdoor_seating=True,
        work_friendly=1,
        date_friendly=4,
        family_friendly=2,
        tags=["live music", "artsy", "lively", "date-friendly"],
    ),
    Place(
        id="terra-kulture",
        name="Terra Kulture",
        category="Culture",
        area="Victoria Island",
        location=Location(lat=6.4263, lng=3.4212),
        price_level=2,
        typical_spend=12000,
        rating=4.5,
        opens_at=9,
        closes_at=22,
        wifi=2,
        power=2,
        quietness=3,
        seating=3,
        ambience=5,
        food=4,
        parking=True,
        security=4,
        outdoor_seating=False,
        work_friendly=2,
        date_friendly=4,
        family_friendly=5,
        tags=["culture", "books", "food", "date-friendly"],
    ),
]
